[package]
name = "pi-ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pi-lexer = { path = "../pi-lexer" }
smol_str = "0.1.21"
