[package]
name = "pi-syntax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pi-lexer = { path = "../pi-lexer" }
num-derive = "0.3.3"
num-traits = "0.2.14"
rowan = "0.15.4"
